/**
 * Colors.kt
 *
 * Material 3 color definitions for the CryptoVault application.
 * This file contains the complete dark theme color palette.
 *
 * CryptoVault is a dark-theme-only application for optimal viewing
 * of financial data and reduced eye strain during extended use.
 *
 * Color palette generated by: https://materialkolor.com
 * Original palette source: https://coolors.co/palette/e63946-f1faee-a8dadc-457b9d-1d3557
 *
 * The palette includes:
 * - Primary colors: Main brand colors and their variants
 * - Secondary colors: Supporting accent colors
 * - Tertiary colors: Additional accent for variety
 * - Error colors: For error states and validation
 * - Surface colors: For backgrounds and containers
 * - Outline colors: For borders and dividers
 *
 * @see Theme.kt for how these colors are used in the color scheme
 */
package com.example.cryptovault.theme

import androidx.compose.ui.graphics.Color

/**
 * Seed color used to generate the Material 3 color palette.
 * Based on a deep navy blue (#1D3557).
 */
internal val Seed = Color(0xFF1D3557)

// ============================================================================
// DARK THEME COLORS (App Default)
// ============================================================================

/** Primary color - light blue */
internal val PrimaryDark = Color(0xFFB0C7F1)
/** Color for content on primary surfaces */
internal val OnPrimaryDark = Color(0xFF183153)
/** Primary container color */
internal val PrimaryContainerDark = Color(0xFF30476A)
/** Color for content on primary container */
internal val OnPrimaryContainerDark = Color(0xFFD5E3FF)

/** Secondary color - light teal */
internal val SecondaryDark = Color(0xFF98CDF2)
/** Color for content on secondary surfaces */
internal val OnSecondaryDark = Color(0xFF00344C)
/** Secondary container color */
internal val SecondaryContainerDark = Color(0xFF064C6B)
/** Color for content on secondary container */
internal val OnSecondaryContainerDark = Color(0xFFC7E7FF)

/** Tertiary color - light teal green */
internal val TertiaryDark = Color(0xFF9ECFD1)
/** Color for content on tertiary surfaces */
internal val OnTertiaryDark = Color(0xFF003739)
/** Tertiary container color */
internal val TertiaryContainerDark = Color(0xFF1A4E50)
/** Color for content on tertiary container */
internal val OnTertiaryContainerDark = Color(0xFFB9ECEE)

/** Error color - light red/pink */
internal val ErrorDark = Color(0xFFFFB3B1)
/** Color for content on error surfaces */
internal val OnErrorDark = Color(0xFF680011)
/** Error container color */
internal val ErrorContainerDark = Color(0xFF92001C)
/** Color for content on error container */
internal val OnErrorContainerDark = Color(0xFFFFDAD8)

/** Background color */
internal val BackgroundDark = Color(0xFF121414)
/** Color for content on background */
internal val OnBackgroundDark = Color(0xFFE2E2E2)
/** Surface color */
internal val SurfaceDark = Color(0xFF121414)
/** Color for content on surface */
internal val OnSurfaceDark = Color(0xFFE2E2E2)
/** Surface variant color */
internal val SurfaceVariantDark = Color(0xFF404941)
/** Color for content on surface variant */
internal val OnSurfaceVariantDark = Color(0xFFC0C9BE)

/** Outline color - for borders */
internal val OutlineDark = Color(0xFF8A9389)
/** Outline variant color */
internal val OutlineVariantDark = Color(0xFF404941)
/** Scrim color - for overlays */
internal val ScrimDark = Color(0xFF000000)

/** Inverse surface color */
internal val InverseSurfaceDark = Color(0xFFE2E2E2)
/** Color for content on inverse surface */
internal val InverseOnSurfaceDark = Color(0xFF2F3131)
/** Inverse primary color */
internal val InversePrimaryDark = Color(0xFF485F84)

/** Dim surface color */
internal val SurfaceDimDark = Color(0xFF121414)
/** Bright surface color */
internal val SurfaceBrightDark = Color(0xFF37393A)
/** Lowest elevation surface container */
internal val SurfaceContainerLowestDark = Color(0xFF0C0F0F)
/** Low elevation surface container */
internal val SurfaceContainerLowDark = Color(0xFF1A1C1C)
/** Standard surface container */
internal val SurfaceContainerDark = Color(0xFF1E2020)
/** High elevation surface container */
internal val SurfaceContainerHighDark = Color(0xFF282A2B)
/** Highest elevation surface container */
internal val SurfaceContainerHighestDark = Color(0xFF333535)